name: Fetch Channel EPG and Generate Text File

on:
  schedule:
    - cron: '30 8 * * *' # Schedule to run at 2 PM IST
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Copy package.json to use fetchEPGpackage.json
        run: cp fetchEPGpackage.json package.json
        
      - name: Copy package.json to use fetchEPGpackage-lock.json
        run: cp fetchEPGpackage-lock.json package-lock.json
        
      - name: Install dependencies from fetchEPGpackage.json
        run: npm ci --no-audit --prefer-offline

      - name: Run Node.js script
        run: node fetchChannelEPG.js

      - name: pull latest
        run: |
          git pull
          
        # Commit all changed files back to the repository
      - name: Commit updated data.txt
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated EPG
