# Workflow to automate deployment of a React app to GitHub Pages

name: Deploy React app to Pages

# Triggers the workflow on pushes to the main branch or manual triggering
on:
  push:
    branches: ["main"]
  workflow_dispatch:

# Define permissions required for GitHub Actions
permissions:
  contents: write
  pages: write
  id-token: write
  
# Configure concurrency settings
concurrency:
  group: "pages"
  cancel-in-progress: false

# Define the jobs within this workflow
jobs:
  # Job to build the React app
  build:
    runs-on: ubuntu-latest
    outputs:
      package-manager: ${{ steps.detect-package-manager.outputs.package-manager }}
    
    steps:
      # Step 1: Checkout the repository code
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: Detect the package manager (Yarn or npm) used in the project
      - name: Detect package manager
        id: detect-package-manager
        run: |
          # Check for lock files to determine the package manager
          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
            echo "manager=yarn" >> $GITHUB_OUTPUT
            echo "command=install" >> $GITHUB_OUTPUT
            echo "runner=yarn" >> $GITHUB_OUTPUT
            exit 0
          elif [ -f "${{ github.workspace }}/package-lock.json" ]; then
            echo "manager=npm" >> $GITHUB_OUTPUT
            echo "command=ci" >> $GITHUB_OUTPUT
            echo "runner=npm" >> $GITHUB_OUTPUT
            exit 0
          else
            echo "Unable to determine package manager"
            exit 1
          fi
          echo "::set-output name=package-manager::npm"

      # Step 3: Setup Node.js environment with Node version 14
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "14"
          cache: ${{ steps.detect-package-manager.outputs.manager }}

      # Step 4: Install dependencies based on the detected package manager
      - name: Install dependencies
        run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}

      # Step 5: Build the React app
      - name: Build React app
        run: ${{ steps.detect-package-manager.outputs.runner }} run build

      # Step 6: Set up Git identity
      - name: Set up Git identity
        run: |
          git config --global user.email "ajay90211@gmail.com"
          git config --global user.name "Ajay"
          
      # Step 7: Deploy the React app
      - name: Deploy React app
        run: ${{ steps.detect-package-manager.outputs.runner }} run deploy




